### ISSUE TITLE
bug: TS2339: Property does not exist on type '(props: Props & InputProps<VModelType> & {}) => any'.

### ISSUE THREAD

**Issue by borisdiakur** [ionic-team/stencil-ds-output-targets#356]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.

### Stencil Version

3.3.1

### Stencil Framework Output Target

Vue

### Stencil Framework Output Target Version

0.8.6

### Current Behavior

We're getting Typescript compilation errors when building the Vue output target after upgrading Vue from 3.2.47 to 3.3.4:

```
Error: out/vue-component-lib/utils.ts(182,13): error TS2339: Property 'displayName' does not exist on type '(props: Props & InputProps<VModelType> & {}) => any'.
Error: out/vue-component-lib/utils.ts(184,13): error TS2339: Property 'props' does not exist on type '(props: Props & InputProps<VModelType> & {}) => any'.
```

References:
- PR containing the Vue upgrade: https://github.com/emdgroup-liquid/liquid/pull/720
- Breaking GitHub action: https://github.com/emdgroup-liquid/liquid/actions/runs/5245133252/jobs/9472143257?pr=720#step:6:63

### Expected Behavior

We expect no typing issues since it's "only" a minor version bump (however, the Vue team admittedly has shipped [a lot of changes](https://blog.vuejs.org/posts/vue-3-3) with that minor version bump 😬).

### Steps to Reproduce

Currently we can offer these steps to reproduce the issue: 

1. Checkout the https://github.com/emdgroup-liquid/liquid/ repository on the main branch
2. Run the build step: `corepack enable && yarn && yarn build` => everything is fine;
3. Upgrade vue to v3.3.4
4. Run `yarn build` again => the build fails.

I'll try to set up a minimal reproduction repo as soon as possible.

### Code Reproduction URL

https://github.com/emdgroup-liquid/liquid

### Additional Information

It looks like the `DefineComponent` `type` is somehow lost after the upgrade.

Before the upgrade:
<img width="846" alt="Screenshot 2023-06-12 at 18 07 05" src="https://github.com/ionic-team/stencil-ds-output-targets/assets/527049/7ea51697-af7d-4844-bd95-cd3dae2dd907">

After the upgrade:
<img width="823" alt="Screenshot 2023-06-12 at 18 06 15" src="https://github.com/ionic-team/stencil-ds-output-targets/assets/527049/ba4111d1-d159-492d-90b6-8a1e54dfa241">

Please let me know if you need further information. 🙏

**Comment by borisdiakur** [comment]
**UPDATE:**

I could resolve the issue for now. Looks like in the newest version there is a [`// @ts-nocheck` comment](https://github.com/ionic-team/stencil-ds-output-targets/commit/f04737d3210ead5fe2d1b150c33f622c960abef7#diff-6c8718b9a07882a0d1c3e344c25c2946d2d36997ef09469219bc7e39d4d43020R1) in the utils.ts file which was missing in our code due to an outdated patch file. I could fix this by [updating the patch file](https://github.com/emdgroup-liquid/liquid/pull/766/files). Closing 🥵. I'm sorry for the noise.
