### ISSUE TITLE
react-component-lib depends on @stencil/core

### ISSUE THREAD

**Issue by sentience** [ionic-team/stencil-ds-output-targets#88]
Having just upgraded to 0.0.7 of the React output target, I got this error in my consuming React project:

>/path/to/react-app/src/react-component-lib/createComponent.tsx
>TypeScript error in /path/to/react-app/src/react-component-lib/createComponent.tsx(10,36):
>Cannot find module '@stencil/core/internal/stencil-public-runtime' or its corresponding type declarations.  TS2307

It looks like a runtime dependency on @stencil/core has been introduced into the build output of react-output-target. That would mean that every React app that consumes React proxies would need to add Stencil to its package.json, which I do not believe is how react-output-target is intended to work (and wasn't the case for 0.0.6).

The dependency was introduced by https://github.com/ionic-team/stencil-ds-output-targets/commit/1b0a49cd1c035cc60fcf82b74f5df44f5fcc60d4#diff-0c5775a0b0c1a17c5b8e386f105c1683R10.

**Comment by viljamis** [comment]
We noticed this change as well. Is this intended?

**Comment by chris-dura** [comment]
The fix #71 seems to be merged into master, and will probably be released with `0.0.8`
https://github.com/ionic-team/stencil-ds-output-targets/issues/97
